// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANO6X7PzTDUWKfdDFt4UBrKq_E17WTUXs',
    appId: '1:378296388470:web:433b88fc66f932ffc2c857',
    messagingSenderId: '378296388470',
    projectId: 'ecommerce-3316e',
    authDomain: 'ecommerce-3316e.firebaseapp.com',
    storageBucket: 'ecommerce-3316e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhVlQVzDeAjiRAJU7H4PO14REV7r1sN2I',
    appId: '1:378296388470:android:39d70086fec97a5fc2c857',
    messagingSenderId: '378296388470',
    projectId: 'ecommerce-3316e',
    storageBucket: 'ecommerce-3316e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXeLA4i855eWszvHxi3R2X0jtsA1LX_8w',
    appId: '1:378296388470:ios:e1bca813e56de682c2c857',
    messagingSenderId: '378296388470',
    projectId: 'ecommerce-3316e',
    storageBucket: 'ecommerce-3316e.appspot.com',
    androidClientId: '378296388470-72p59o8t45gtpgeepse45cgf2drbts9h.apps.googleusercontent.com',
    iosClientId: '378296388470-9422qcip8aig52s3080u7mqtl8ginm2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
